# Generated by Django 3.2.7 on 2021-12-14 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0004_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='average',
            new_name='avarage_rate',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='content',
            new_name='content_rate',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='design',
            new_name='design_rate',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='usability',
            new_name='usability_rate',
        ),
    ]
