# Generated by Django 3.2.7 on 2021-12-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0005_auto_20211214_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='avarage_rate',
            new_name='average',
        ),
    ]
