# Generated by Django 3.2.7 on 2021-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardsapp', '0006_rename_avarage_rate_rating_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
